"""
Clean Excel → Google Sheet loader.
Writes TENANTS + monthly tabs ONLY. Dashboard generated by Apps Script.

Rules (from SHEET_LOGIC.md):
- Cash/UPI: from columns only, never comments
- Balance: clean text (exit dates=0, returns=0, Chandra=parallel amount)
- Occupancy: Active + checkin <= month_end. No-show: ALL, no date filter.
- Status: from rent status column as-is
- Chandra/Lakshmi: tracked in separate columns (N, O) for Apps Script to read
"""
import sys, os, re, time
sys.stdout.reconfigure(encoding='utf-8')
from datetime import date, datetime
from collections import Counter
import openpyxl
import gspread
from google.oauth2.service_account import Credentials

EXCEL_FILE = "Cozeevo Monthly stay (4).xlsx"
NEW_SHEET = "1Hp5dTM7TcDEq75jgHEjvwtBjOolruGfQ7CVMzVqjdGw"
CREDS = "credentials/gsheets_service_account.json"
TOTAL_BEDS = 296  # updated 2026-05-17; G16 max_occupancy fixed to 1

# ── Shared functions (identical to full_report.py) ───────────────────────────

def sn(v):
    if v is None: return 0
    try: return float(v)
    except: return 0

def parse_date(v):
    if v is None: return None
    if isinstance(v, datetime): return v.date()
    if isinstance(v, date): return v
    s = str(v).strip()
    for fmt in ('%d-%m-%Y', '%d-%m-%y', '%Y-%m-%d', '%d/%m/%Y', '%d/%m/%y'):
        try: return datetime.strptime(s, fmt).date()
        except: continue
    return None

def clean_status(v):
    s = str(v).strip().upper() if v else ''
    if s in ('CHECKIN', 'CHECK IN', ''): return 'Active'
    if 'EXIT' in s: return 'Exited'
    if 'NO SHOW' in s: return 'No-show'
    if 'CANCEL' in s: return 'Cancelled'
    return 'Active'

def rent_status(v):
    s = str(v).strip().upper() if v else ''
    if not s: return ''
    if 'PAID' in s and 'NOT' not in s and 'PARTIAL' not in s: return 'PAID'
    if 'PARTIAL' in s: return 'PARTIAL'
    if 'NOT PAID' in s or 'UNPAID' in s: return 'UNPAID'
    if 'EXIT' in s: return 'EXIT'
    if 'NO SHOW' in s: return 'NO SHOW'
    if 'ADVANCE' in s: return 'ADVANCE'
    if 'CANCEL' in s: return 'CANCELLED'
    return s

CHANDRA_RE = re.compile(r'received\s+by\s+chandra', re.I)
EXIT_PATS = [
    re.compile(r'(?:march|feb|jan|apr)\w*\s+\d+\s*(?:st|nd|rd|th)?\s*(?:\d+\s*(?:am|pm)\s+)?exit', re.I),
    re.compile(r'exit\s+on\s+', re.I),
    re.compile(r'\bexit\s*$', re.I),
]

def clean_num(raw, is_balance=False, cash_num=0, upi_num=0, rent=0):
    """Clean a cell. Returns (number, note, chandra_amt, lakshmi_amt).
    IDENTICAL to full_report.py — do not modify one without the other."""
    if raw is None: return 0, '', 0, 0
    s = str(raw).strip()
    if not s: return 0, '', 0, 0
    try: return float(s), '', 0, 0
    except: pass

    # Chandra in balance col: return 0 for balance, track separately
    if is_balance and CHANDRA_RE.search(s):
        amt = cash_num if cash_num > 0 else (upi_num if upi_num > 0 else rent)
        return 0, s, amt, 0
    # Chandra in cash col: return 0 for cash, track separately
    if not is_balance and CHANDRA_RE.search(s):
        sp = re.match(r'(\d[\d,]*)\s*Received.*?/\s*(\d[\d,]*)\s*(.*)', s, re.I)
        if sp:
            a1 = float(sp.group(1).replace(',', ''))
            a2 = float(sp.group(2).replace(',', ''))
            return 0, s, a1, a2
        amt = upi_num if upi_num > 0 else rent
        return 0, s, amt, 0
    # Exit dates = 0
    for p in EXIT_PATS:
        if p.search(s): return 0, s, 0, 0
    # Return = refund, not balance
    if re.match(r'return\s+\d+', s, re.I): return 0, s, 0, 0
    # paid in X = 0
    if re.match(r'paid\s+in\s+', s, re.I): return 0, s, 0, 0
    # hitachi = 0
    if re.match(r'hitachi', s, re.I): return 0, s, 0, 0
    # dash = 0
    if s == '-': return 0, '-', 0, 0
    # Expression: 516*16=8256
    eq = re.search(r'=\s*([\d,.]+)\s*$', s)
    if eq: return float(eq.group(1).replace(',', '')), s, 0, 0
    # Number + text: "5500 on april 1st", "9000 deposit"
    m = re.search(r'([\d,]+)', s)
    if m: return float(m.group(1).replace(',', '')), s, 0, 0
    return 0, s, 0, 0

def safe_str(v):
    if v is None: return ''
    s = str(v).strip()
    if s.endswith('.0'):
        try: return str(int(float(s)))
        except: pass
    return s

# ── Google Sheet helpers ─────────────────────────────────────────────────────

def get_ws(sp, name, rows=300, cols=20):
    try:
        ws = sp.worksheet(name)
        ws.clear()
    except gspread.WorksheetNotFound:
        ws = sp.add_worksheet(name, rows=rows, cols=cols)
    return ws

# ── Main ─────────────────────────────────────────────────────────────────────

def read_history(excel_file=EXCEL_FILE):
    """Parse History sheet → list of tenant dicts.
    This is the SINGLE parser — used by both clean_and_load.py and excel_import.py.
    """
    wb = openpyxl.load_workbook(excel_file, data_only=True)
    ws = wb['History']

    tenants = []
    for row in range(2, ws.max_row + 1):
        name = ws.cell(row, 2).value
        if not name or not str(name).strip(): continue

        rm = sn(ws.cell(row, 10).value)
        rf = sn(ws.cell(row, 11).value)
        ry = sn(ws.cell(row, 12).value)
        rent = ry if ry > 0 else (rf if rf > 0 else rm)

        tenants.append({
            'name': str(name).strip(),
            'room': safe_str(ws.cell(row, 1).value),
            'phone': safe_str(ws.cell(row, 4).value),
            'gender': safe_str(ws.cell(row, 3).value),
            'block': safe_str(ws.cell(row, 18).value),
            'floor': safe_str(ws.cell(row, 19).value),
            'sharing': safe_str(ws.cell(row, 13).value),
            'checkin_raw': safe_str(ws.cell(row, 5).value),
            'checkin': parse_date(ws.cell(row, 5).value),
            'status': clean_status(ws.cell(row, 17).value),
            'rent_monthly': rm, 'rent_feb': rf, 'rent_may': ry,
            'current_rent': rent,
            'deposit': sn(ws.cell(row, 7).value),
            'booking': sn(ws.cell(row, 6).value),
            'maintenance': sn(ws.cell(row, 8).value),
            'staff': safe_str(ws.cell(row, 16).value),
            'comment': safe_str(ws.cell(row, 15).value),
            'food': safe_str(ws.cell(row, 36).value),          # Col 36 = veg/nonveg/egg
            'rent_updated': safe_str(ws.cell(row, 39).value),    # Col 39 = Rent Updated
            'refund_status': safe_str(ws.cell(row, 40).value),  # Col 40 = Refund Status
            'refund_amount': sn(ws.cell(row, 41).value),        # Col 41 = Refund Amount
            # Raw payment values (cleaned later per-month)
            'dec_st': rent_status(ws.cell(row, 21).value),      # Col 21 = DEC RENT
            'jan_st': rent_status(ws.cell(row, 22).value),      # Col 22 = JAN RENT
            'jan_bal': ws.cell(row, 23).value, 'jan_cash': ws.cell(row, 24).value, 'jan_upi': ws.cell(row, 25).value,  # Col 23-25
            'feb_st': rent_status(ws.cell(row, 26).value),      # Col 26 = FEB RENT
            'feb_bal': ws.cell(row, 29).value, 'feb_cash': ws.cell(row, 30).value, 'feb_upi': ws.cell(row, 31).value,  # Col 29-31
            'mar_st': rent_status(ws.cell(row, 27).value),      # Col 27 = MARCH RENT
            'mar_bal': ws.cell(row, 32).value, 'mar_cash': ws.cell(row, 33).value, 'mar_upi': ws.cell(row, 34).value,  # Col 32-34
            'apr_st_raw': rent_status(ws.cell(row, 28).value),  # Col 28 = April
        })

    # April status: use Excel column if available, else generate from tenant status
    for t in tenants:
        raw = t.get('apr_st_raw', '')
        if raw and raw not in ('', 'None'):
            t['apr_st'] = raw
        elif t['status'] == 'Active':
            t['apr_st'] = 'UNPAID'
        elif t['status'] == 'No-show':
            t['apr_st'] = 'NO SHOW'
        elif t['status'] == 'Exited':
            t['apr_st'] = 'EXIT' if t.get('mar_st') != 'EXIT' else ''
        else:
            t['apr_st'] = ''
        t['apr_cash'] = 0
        t['apr_upi'] = 0
        t['apr_bal'] = 0

    return tenants


def main():
    print("Step 1: Reading Excel...")
    tenants = read_history()
    print(f"  {len(tenants)} tenants parsed")

    # Sort by check-in ascending so every tab (TENANTS + monthly) has latest check-in at the bottom.
    # None/missing check-ins sink to the top so the real latest stays last.
    tenants.sort(key=lambda t: (t.get('checkin') or date.min, str(t.get('room', '')), str(t.get('name', ''))))

    # No-show count is calculated per-month (only those whose checkin >= month start)

    # ── Step 2: Write to Google Sheet ────────────────────────────────────
    print("\nStep 2: Writing to Google Sheet...")
    creds = Credentials.from_service_account_file(CREDS,
        scopes=['https://www.googleapis.com/auth/spreadsheets'])
    gc = gspread.authorize(creds)
    sp = gc.open_by_key(NEW_SHEET)

    # ── TENANTS tab (DB-aligned: tenants + tenancies + rooms) ────────────
    # Import canonical headers from gsheets (single source of truth)
    from src.integrations.gsheets import TENANTS_HEADERS, MONTHLY_HEADERS

    ws_t = get_ws(sp, "TENANTS", 300, len(TENANTS_HEADERS) + 1)
    t_headers = TENANTS_HEADERS
    t_rows = [[
        t['room'], t['name'], f"'{t['phone']}" if t['phone'] else '', t['gender'],
        t['block'], t['floor'],
        t['sharing'], t['checkin_raw'], t['status'], t['current_rent'],
        t['deposit'], t['booking'], t['maintenance'],
        '', '', '',
        t.get('refund_status', ''), sn(t.get('refund_amount', 0)) or '',
        '', '', '', '',                                                 # DOB-Address (KYC — via bot)
        '', '', '',                                                     # Emergency, Relationship, Email
        '', '', '', '',                                                 # Occupation-Office Phone
        '', '', t.get('food', ''),                                      # ID Type, ID Number, Food Pref
        t.get('comment', ''), 'CHECKIN' if t['status'] == 'Active' else '',  # Notes, Event
    ] for t in tenants]

    ws_t.update(values=[t_headers] + t_rows, range_name="A1", value_input_option="USER_ENTERED")
    ws_t.format("A1:AH1", {"textFormat": {"bold": True},
                            "backgroundColor": {"red": 0.85, "green": 0.95, "blue": 0.85}})
    ws_t.freeze(rows=1)
    try: ws_t.set_basic_filter(f"A1:AH{1 + len(t_rows)}")
    except: pass
    print(f"  TENANTS: {len(t_rows)} rows")
    time.sleep(8)

    # ── Monthly tabs ─────────────────────────────────────────────────────
    months_cfg = [
        ("DECEMBER 2025", date(2025,12,1), date(2025,12,31), 'dec_st', None, None, None),
        ("JANUARY 2026",  date(2026,1,1),  date(2026,1,31),  'jan_st', 'jan_cash', 'jan_upi', 'jan_bal'),
        ("FEBRUARY 2026", date(2026,2,1),  date(2026,2,28),  'feb_st', 'feb_cash', 'feb_upi', 'feb_bal'),
        ("MARCH 2026",    date(2026,3,1),  date(2026,3,31),  'mar_st', 'mar_cash', 'mar_upi', 'mar_bal'),
        ("APRIL 2026",    date(2026,4,1),  date(2026,4,30),  'apr_st', 'apr_cash', 'apr_upi', 'apr_bal'),
    ]

    for label, ms, me, stk, ck, uk, bk in months_cfg:
        # April+ uses new 17-col format (from MONTHLY_HEADERS canonical source)
        use_new_fmt = (ms >= date(2026, 4, 1))
        if use_new_fmt:
            headers = MONTHLY_HEADERS
        else:
            # Legacy format for Dec-Mar (no Phone, Notice Date, Entered By)
            headers = ["Room", "Name", "Building", "Sharing", "Rent",
                       "Cash", "UPI", "Total Paid", "Balance",
                       "Status", "Check-in", "Event", "Notes", "Chandra", "Lakshmi"]
        ncols = len(headers) + 1
        ws_m = get_ws(sp, label, 300, ncols)

        # Clean payments for this month
        m_rows = []
        cash_total = 0; upi_total = 0; bal_total = 0
        chandra_total = 0; lakshmi_total = 0
        new_checkins = 0; exits = 0

        for t in tenants:
            st = t.get(stk, '')
            has_payment = False
            cash = 0; upi = 0; bal = 0; notes_parts = []
            t_chandra = 0; t_lakshmi = 0

            if ck:
                cash_num = sn(t[ck]) if isinstance(t[ck], (int, float)) else 0
                upi_num = sn(t[uk]) if isinstance(t[uk], (int, float)) else 0

                cash, cn, cc, cl = clean_num(t[ck], False, 0, upi_num, t['current_rent'])
                upi, un, _, _ = clean_num(t[uk])
                bal, bn, bc, bl = clean_num(t[bk], True, cash_num, upi_num, t['current_rent'])

                if cn: notes_parts.append(cn)
                if un: notes_parts.append(un)
                if bn: notes_parts.append(bn)

                t_chandra = cc + bc
                t_lakshmi = cl + bl
                chandra_total += t_chandra
                lakshmi_total += t_lakshmi
                has_payment = cash > 0 or upi > 0

            # Who appears in this month?
            # NO SHOW: show in EVERY month from first appearance until checkin month.
            # A no-show bed is reserved and not available — must count in occupancy.
            actual_noshow = (t['status'] == 'No-show' and t['checkin']
                             and t['checkin'] >= ms)  # checkin is this month or later
            is_meaningful = st in ('PAID', 'PARTIAL', 'UNPAID', 'ADVANCE') or actual_noshow

            # EXIT: only include if this is the first month with EXIT
            if st == 'EXIT':
                prev_months = {'dec_st': None, 'jan_st': 'dec_st', 'feb_st': 'jan_st', 'mar_st': 'feb_st', 'apr_st': 'mar_st'}
                prev_key = prev_months.get(stk)
                prev_st = t.get(prev_key, '') if prev_key else ''
                if prev_st == 'EXIT':
                    pass  # Previous month already had EXIT, skip
                else:
                    is_meaningful = True

            if not (has_payment or is_meaningful):
                continue

            total_paid = cash + upi
            notes = t.get('comment', '')

            # Event
            event = ""
            if t['checkin'] and ms <= t['checkin'] <= me:
                if t['status'] == 'No-show' or st == 'NO SHOW':
                    event = "NO-SHOW"
                else:
                    event = "NEW CHECK-IN"
                    new_checkins += 1
            if st == 'EXIT':
                event = "EXITED" if not event else event + " + EXITED"
                exits += 1

            cash_total += cash
            upi_total += upi
            bal_total += bal

            # For April onwards: use formulas for Total Paid, Balance, Status
            data_row_num = len(m_rows) + 5  # summary rows 1-3, header row 4, data starts row 5
            use_formulas = (ms >= date(2026, 4, 1))

            if use_new_fmt:
                # New 17-col format with Phone column, formulas for Apr+
                f_total = f'=G{data_row_num}+H{data_row_num}'
                f_bal   = f'=F{data_row_num}+P{data_row_num}-I{data_row_num}'
                f_st    = f'=IF(I{data_row_num}=0,"UNPAID",IF(J{data_row_num}<=0,"PAID","PARTIAL"))'
                m_rows.append([
                    t['room'], t['name'], f"'{t['phone']}" if t['phone'] else '',
                    t['block'], t['sharing'],
                    t['current_rent'], cash, upi, f_total, f_bal,
                    f_st, t['checkin_raw'], '', event, notes, 0, 'excel_load',
                ])
            elif use_formulas:
                f_total = f'=F{data_row_num}+G{data_row_num}'
                f_bal   = f'=E{data_row_num}-H{data_row_num}'
                f_st    = f'=IF(I{data_row_num}<=0,"PAID","UNPAID")'
                m_rows.append([
                    t['room'], t['name'], t['block'], t['sharing'],
                    t['current_rent'], cash, upi, f_total, f_bal,
                    f_st, t['checkin_raw'], event, notes, t_chandra, t_lakshmi,
                ])
            else:
                m_rows.append([
                    t['room'], t['name'], t['block'], t['sharing'],
                    t['current_rent'], cash, upi, total_paid, bal,
                    st, t['checkin_raw'], event, notes, t_chandra, t_lakshmi,
                ])

        # Occupancy for this month
        active = [t for t in tenants if t['status'] == 'Active' and t['checkin'] and t['checkin'] <= me]
        prem_a = sum(1 for t in active if str(t['sharing']).lower() == 'premium')
        reg_a = len(active) - prem_a
        a_beds = reg_a + prem_a * 2

        # No-show beds for THIS month: checkin >= month start (bed reserved, not available)
        month_noshow = [t for t in tenants if t['status'] == 'No-show' and t['checkin'] and t['checkin'] >= ms]
        ns_prem = sum(1 for t in month_noshow if str(t['sharing']).lower() == 'premium')
        ns_beds = (len(month_noshow) - ns_prem) + ns_prem * 2

        vacant = TOTAL_BEDS - a_beds - ns_beds

        # THOR/HULK
        thor = [t for t in active if t['block'] == 'THOR']
        hulk = [t for t in active if t['block'] == 'HULK']
        tp = sum(1 for t in thor if str(t['sharing']).lower() == 'premium')
        hp = sum(1 for t in hulk if str(t['sharing']).lower() == 'premium')
        tb = (len(thor) - tp) + tp * 2
        hb = (len(hulk) - hp) + hp * 2

        # Status counts
        stc = Counter(t.get(stk, '') for t in tenants if t.get(stk, ''))

        collected = cash_total + upi_total

        # Summary rows (rows 1-4, then data from row 5)
        pad = len(headers)
        if use_new_fmt:
            summary = [
                [label] + [""] * (pad - 1),
                [
                    "Checked-in", f"{a_beds} beds ({reg_a}+{prem_a}P)",
                    "", f"No-show: {ns_beds} beds ({len(month_noshow)}t)",
                    f"Vacant: {vacant}", f"Occ: {a_beds/TOTAL_BEDS*100:.1f}%",
                    "Cash", cash_total, "UPI", upi_total, "Total", collected,
                    "", f"Bal: {bal_total:,.0f}", "", "", "",
                ],
                [
                    f"THOR: {tb}b ({len(thor)}t,{tp}P)", f"HULK: {hb}b ({len(hulk)}t,{hp}P)",
                    "", f"New: {new_checkins}", f"Exit: {exits}",
                    f"PAID:{stc.get('PAID',0)}", f"PARTIAL:{stc.get('PARTIAL',0)}",
                    f"UNPAID:{stc.get('UNPAID',0)}", f"NS:{stc.get('NO SHOW',0)}",
                    f"EXIT:{stc.get('EXIT',0)}", "", "", "", "", "", "", "",
                ],
                headers,
            ]
        else:
            summary = [
                [label] + [""] * (pad - 1),
                [
                    "Checked-in", f"{a_beds} beds ({reg_a}+{prem_a}P)",
                    f"No-show: {ns_beds} beds ({len(month_noshow)}t)",
                    f"Vacant: {vacant}", f"Occ: {a_beds/TOTAL_BEDS*100:.1f}%",
                    "Cash", cash_total, "UPI", upi_total, "Total", collected,
                    f"Bal: {bal_total:,.0f}", f"Chandra: {chandra_total:,.0f}",
                    f"Lakshmi: {lakshmi_total:,.0f}", "",
                ],
                [
                    f"THOR: {tb}b ({len(thor)}t,{tp}P)", f"HULK: {hb}b ({len(hulk)}t,{hp}P)",
                    f"New: {new_checkins}", f"Exit: {exits}",
                    f"PAID:{stc.get('PAID',0)}", f"PARTIAL:{stc.get('PARTIAL',0)}",
                    f"UNPAID:{stc.get('UNPAID',0)}", f"NS:{stc.get('NO SHOW',0)}",
                    f"EXIT:{stc.get('EXIT',0)}", "", "", "", "", "", "",
                ],
                headers,
            ]

        last_col = chr(ord('A') + pad - 1) if pad <= 26 else 'Q'
        ws_m.update(values=summary + m_rows, range_name="A1", value_input_option="USER_ENTERED")
        ws_m.format(f"A1:{last_col}1", {"textFormat": {"bold": True, "fontSize": 13}})
        ws_m.format(f"A2:{last_col}3", {"textFormat": {"bold": True, "fontSize": 9},
                               "numberFormat": {"type": "NUMBER", "pattern": "#,##0"}})
        ws_m.format(f"A4:{last_col}4", {"textFormat": {"bold": True},
                               "backgroundColor": {"red": 0.85, "green": 0.9, "blue": 1.0}})
        ws_m.freeze(rows=4)
        try: ws_m.set_basic_filter(f"A4:{last_col}{4 + len(m_rows)}")
        except: pass

        print(f"  {label}: {len(m_rows)}t | Beds:{a_beds} NS:{ns_beds} V:{vacant} | "
              f"Cash:{cash_total:,.0f} UPI:{upi_total:,.0f} | "
              f"Chandra:{chandra_total:,.0f} Lakshmi:{lakshmi_total:,.0f} Dues:{bal_total:,.0f}")
        time.sleep(8)

    # ── Cleanup old tabs ─────────────────────────────────────────────────
    for name in ["Sheet1", "ROOMS", "PAYMENTS", "CHANGES LOG", "MONTHLY VIEW",
                 "MONTHLY JAN 2026", "MONTHLY FEB 2026", "_LOOKUP", "COLLECT RENT"]:
        try: sp.del_worksheet(sp.worksheet(name))
        except: pass

    print(f"\n{'='*60}")
    print("DONE! Tabs: TENANTS, DECEMBER-MARCH (with Chandra/Lakshmi cols)")
    print("Dashboard: Go to Google Sheet > Cozeevo menu > Refresh Dashboard")


if __name__ == "__main__":
    main()
